services:
  - type: web
    name: learning-platform
    env: docker
    plan: free
    region: ohio
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learning-db
          property: connectionString

databases:
  - name: learning-db
    databaseName: learningplatform
    user: admin
    plan: free
    region: ohio
